### ISSUE TITLE
It's not working, it just shows a blue and yellow placeholder model, even after removing "main" from it, I'm using Mac

### ISSUE THREAD

**Issue by DEBUNKED115** [sriemmanuel787/737-MAX#33]
So I just downloaded it just now, the plane doesn't work, it only shows the placeholder model instead, I tried to customise it to work, nothing changed

**Comment by SP-NTX** [comment]
what version of max

**Comment by DEBUNKED115** [comment]
All of them, I somehow managed to get it to work with a bit of editing but I ran to another problem, the cockpit is all white and the walls are all black, even the outside is black, it applies an all versions of the plane

**Comment by sriemmanuel787** [comment]
The issue that you have reported occurs with some Mac users, and I'm not sure why this bug occurs yet. I will close this issue now, since there is a similar one open on #12 .
