### ISSUE TITLE
Fix lighting

### ISSUE THREAD

**Issue by DEBUNKED115** [sriemmanuel787/737-MAX#34]
During daytime and nighttime the cockpit seems to be black and white as some buttons are very difficult to see and makes the plane look somewhat ugly, it's still flyable

**Comment by Sadia2000** [comment]
I am not part of the development team but IIRC the aircraft's cockpit is right now not supposed to be very good looking, as its under development at a major scale.

**Comment by SP-NTX** [comment]
exactly

**Comment by sriemmanuel787** [comment]
Thanks for putting this issue out there, but there is already another issue open similar to this that I will tag whenever I make a commit relevant to it, so I'm going to close this now.
