### ISSUE TITLE
Cockpit Location in 73X-7

### ISSUE THREAD

**Issue by Sadia2000** [sriemmanuel787/737-MAX#7]
![fgfs-20221229062358](https://user-images.githubusercontent.com/72543220/209912350-523079f7-f943-417d-9744-961a16799916.png)

As visible, the position of the cockpit has to be modified for the 737-7 MAX.

**Comment by sriemmanuel787** [comment]
Thank you Sadia2000. This is a known issue, and it will be fixed in the next commit.
